feat(tests): add exdev tests
musikid/pjdfstest pull request #131
Opened 2022-12-11 20:38 UTC by musikid

2023-01-01 23:45 UTC, asomers requested changes
This looks pretty good.  Is there any reason that it's still in the "draft" state?  Also, we should probably change the CI configuration to get coverage for this.

2023-01-01 23:45 UTC, asomers commented on rust/src/tests/errors/exdev.rs
> +        .ok_or_else(|| anyhow::anyhow!("No secondary file-system has been configured."))
simplification:
```suggestion
        .map_or_else(|| Err(anyhow::anyhow!("No secondary file-system has been configured.")), drop)
```

2023-01-02 18:38 UTC, musikid commented
Yes, that's the reason why I let it as a draft, I wasn't sure on how to configure the CI for this, especially with the Docker problems with mounts.

2023-01-02 20:29 UTC, asomers approved these changes
I suggest you merge it as-is, and then I'll add the secondary file system for CI.

2023-01-06 20:42 UTC, merged